### ISSUE TITLE
Modmode Not working correctly with 1.7.10

### ISSUE THREAD

**Issue by DOKDOR** [NerdNu/ModMode#11]
Moblimiter wont even load, getting the following error on server startup:

[03:48:57 ERROR]: Could not load 'plugins/ModMode.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: de/bananaco/bpermissions/imp/Permissions
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-1589]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-1589]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-1589]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1589]
Caused by: java.lang.NoClassDefFoundError: de/bananaco/bpermissions/imp/Permissions
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_11]
        at java.lang.Class.forName(Class.java:340) ~[?:1.8.0_11]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-1589]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1589]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: de.bananaco.bpermissions.imp.Permissions
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_11]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_11]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_11]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_11]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1589]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1589]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_11]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_11]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_11]
        at java.lang.Class.forName(Class.java:340) ~[?:1.8.0_11]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-1589]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1589]
        ... 6 more

running CraftBukkit version git-Spigot-1589 (MC: 1.7.10)
and the latest build from jenkins
